// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb7fpTposZOG2W-hSnfTFzftOU3U36zHk',
    appId: '1:392828601618:web:afae13b2f560a1efb6dfcb',
    messagingSenderId: '392828601618',
    projectId: 'campus-bus-62ef1',
    authDomain: 'campus-bus-62ef1.firebaseapp.com',
    storageBucket: 'campus-bus-62ef1.firebasestorage.app',
    measurementId: 'G-JL0NMXJF3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkLRbd2-ObcMM3biAn7uDSOrLiwZF7zK8',
    appId: '1:392828601618:android:7bead6e7a20dc413b6dfcb',
    messagingSenderId: '392828601618',
    projectId: 'campus-bus-62ef1',
    storageBucket: 'campus-bus-62ef1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe-n-DhkYU0Q6UYO-G4zoz0KRCH9Ae8kQ',
    appId: '1:392828601618:ios:1097ec7c4d05531cb6dfcb',
    messagingSenderId: '392828601618',
    projectId: 'campus-bus-62ef1',
    storageBucket: 'campus-bus-62ef1.firebasestorage.app',
    iosBundleId: 'com.example.campusBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe-n-DhkYU0Q6UYO-G4zoz0KRCH9Ae8kQ',
    appId: '1:392828601618:ios:1097ec7c4d05531cb6dfcb',
    messagingSenderId: '392828601618',
    projectId: 'campus-bus-62ef1',
    storageBucket: 'campus-bus-62ef1.firebasestorage.app',
    iosBundleId: 'com.example.campusBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb7fpTposZOG2W-hSnfTFzftOU3U36zHk',
    appId: '1:392828601618:web:1b4845e40aaa4386b6dfcb',
    messagingSenderId: '392828601618',
    projectId: 'campus-bus-62ef1',
    authDomain: 'campus-bus-62ef1.firebaseapp.com',
    storageBucket: 'campus-bus-62ef1.firebasestorage.app',
    measurementId: 'G-C6NCN0CSX7',
  );
}
